/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    areas: Area;
    issues: Issue;
    'directory-entries': DirectoryEntry;
    committees: Committee;
    people: Person;
    posts: Post;
    events: Event;
    memberships: Membership;
    payments: Payment;
    'issue-reports': IssueReport;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    areas: AreasSelect<false> | AreasSelect<true>;
    issues: IssuesSelect<false> | IssuesSelect<true>;
    'directory-entries': DirectoryEntriesSelect<false> | DirectoryEntriesSelect<true>;
    committees: CommitteesSelect<false> | CommitteesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'issue-reports': IssueReportsSelect<false> | IssueReportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'main-navigation': MainNavigation;
    'issue-categories': IssueCategory;
    homepage: Homepage;
    'about-page': AboutPage;
    'membership-page': MembershipPage;
    'page-intros': PageIntro;
    'legal-pages': LegalPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'main-navigation': MainNavigationSelect<false> | MainNavigationSelect<true>;
    'issue-categories': IssueCategoriesSelect<false> | IssueCategoriesSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'membership-page': MembershipPageSelect<false> | MembershipPageSelect<true>;
    'page-intros': PageIntrosSelect<false> | PageIntrosSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  category:
    | 'annual-report'
    | 'meeting-minutes'
    | 'position-paper'
    | 'county-notice'
    | 'environmental-resource'
    | 'planning-guideline'
    | 'public-participation'
    | 'press-release';
  summary?: string | null;
  publishedDate: string;
  visibility: 'public' | 'membersOnly';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas".
 */
export interface Area {
  id: number;
  name: string;
  /**
   * URL-friendly identifier, e.g. "diani"
   */
  slug: string;
  heroImage?: (number | null) | Media;
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  keyServices?:
    | {
        service?: string | null;
        id?: string | null;
      }[]
    | null;
  attractions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Auto-filled by geocoding the area name. Used as the map fallback center for directory entries and issues in this area that have no location of their own. Edit these manually if the auto-placed pin lands somewhere wrong — a manual value is never overwritten.
   */
  location?: {
    lat?: number | null;
    lng?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues".
 */
export interface Issue {
  id: number;
  title: string;
  slug: string;
  category:
    | 'roads-infrastructure'
    | 'security'
    | 'water-supply'
    | 'electricity'
    | 'waste-management'
    | 'environment'
    | 'beach-access'
    | 'planning-development';
  status: 'received' | 'under-review' | 'in-progress' | 'resolved';
  area?: (number | null) | Area;
  /**
   * Specific site of this issue, e.g. "Diani Beach Road near the Nakumatt roundabout". Leave blank to show this issue at its area's general location on the map.
   */
  locationText?: string | null;
  /**
   * Auto-filled by geocoding the location text above. Edit manually if the auto-placed pin lands somewhere wrong — a manual value is never overwritten.
   */
  location?: {
    lat?: number | null;
    lng?: number | null;
  };
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  background: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  actionsUndertaken?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  progressUpdates?:
    | {
        date: string;
        update: string;
        id?: string | null;
      }[]
    | null;
  supportingDocuments?: (number | Document)[] | null;
  relatedNews?: (number | Post)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedIssues?: (number | Issue)[] | null;
  publishedDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directory-entries".
 */
export interface DirectoryEntry {
  id: number;
  name: string;
  category:
    | 'hospitals'
    | 'police'
    | 'emergency'
    | 'utilities'
    | 'schools'
    | 'government'
    | 'member-business'
    | 'professional-services';
  area?: (number | null) | Area;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  description?: string | null;
  /**
   * Auto-filled by geocoding the address above. Falls back to the linked area's location on the map if left blank. Edit manually if the auto-placed pin lands somewhere wrong — a manual value is never overwritten.
   */
  location?: {
    lat?: number | null;
    lng?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees".
 */
export interface Committee {
  id: number;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * e.g. "Chairperson", "Treasurer"
   */
  role: string;
  committee?: (number | null) | Committee;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  eventType:
    'public-participation' | 'community-event' | 'environmental-activity' | 'committee-meeting' | 'public-notice';
  area?: (number | null) | Area;
  startDate: string;
  endDate?: string | null;
  location?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  visibility: 'public' | 'membersOnly';
  updatedAt: string;
  createdAt: string;
}
/**
 * Active/expired status is computed from expiryDate + adminRevoked, not stored here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  /**
   * Auto-assigned on create if left blank. Legacy numbers preserve exact zero-padding.
   */
  membershipNumber?: string | null;
  type: 'personal' | 'household' | 'corporate' | 'free';
  /**
   * Manual override, independent of expiryDate.
   */
  adminRevoked?: boolean | null;
  revokedReason?: string | null;
  primaryContact: {
    surname: string;
    firstName?: string | null;
    phone?: string | null;
    /**
     * Optional for legacy imports; required for any new portal signup.
     */
    email?: string | null;
  };
  postalAddress?: string | null;
  town?: string | null;
  postalCode?: string | null;
  corporateBusinessName?: string | null;
  /**
   * Household: names only. Corporate: up to 4, each may carry its own phone/email for a linked portal account.
   */
  additionalMembers?:
    | {
        surname: string;
        firstName?: string | null;
        phone?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Stored per-record so future rate changes do not rewrite history.
   */
  subscriptionAmount?: number | null;
  /**
   * Single source of truth for active/expired.
   */
  expiryDate: string;
  importStatus: 'native' | 'imported';
  /**
   * Free text for anything ambiguous carried forward from a source import, for secretariat review.
   */
  importFlags?: string | null;
  /**
   * Better Auth users live in a separate Postgres schema outside Payload's collection registry, so this can't be a native relationship field. Populated only once an account actually exists.
   */
  linkedAuthUsers?:
    | {
        authUserId: string;
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Idempotency marker for the renewal-reminder cron — not a status field.
   */
  lastReminderStage?: ('none' | '30day' | '7day' | 'dueday' | 'lapsed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  membership: number | Membership;
  amount: number;
  method: 'stk_push' | 'bank_transfer' | 'cash' | 'other';
  provider: 'tuma' | 'manual';
  /**
   * From Tuma's STK push response.
   */
  tumaPaymentId?: string | null;
  paymentStatus: 'pending' | 'confirmed' | 'failed';
  confirmedAt?: string | null;
  /**
   * Null if confirmed by webhook; set if secretariat manually reconciled it.
   */
  confirmedBy?: (number | null) | User;
  /**
   * Raw Tuma callback body, for audit/debugging.
   */
  rawWebhookPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  paymentType: 'new' | 'renewal';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issue-reports".
 */
export interface IssueReport {
  id: number;
  /**
   * Auto-generated (e.g. SCRA-2847). How anonymous reporters check status without an account.
   */
  referenceCode?: string | null;
  reporterName: string;
  reporterPhone?: string | null;
  reporterEmail?: string | null;
  /**
   * Better Auth user id, set only if logged in at submission — not a Payload relationship, since Better Auth users live in a separate schema.
   */
  reportedBy?: string | null;
  category: 'roads' | 'security' | 'street_lighting' | 'illegal_development' | 'environmental' | 'other';
  description: string;
  photos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Real coordinates captured from day one for the future map layer.
   */
  location?: {
    lat?: number | null;
    lng?: number | null;
    addressText?: string | null;
  };
  status: 'received' | 'under_review' | 'in_progress' | 'resolved';
  /**
   * Audit trail powering the reporter-facing timeline.
   */
  statusHistory?:
    | {
        status: 'received' | 'under_review' | 'in_progress' | 'resolved';
        changedAt: string;
        changedBy?: (number | null) | User;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  linkedIssue?: (number | null) | Issue;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'areas';
        value: number | Area;
      } | null)
    | ({
        relationTo: 'issues';
        value: number | Issue;
      } | null)
    | ({
        relationTo: 'directory-entries';
        value: number | DirectoryEntry;
      } | null)
    | ({
        relationTo: 'committees';
        value: number | Committee;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'issue-reports';
        value: number | IssueReport;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  summary?: T;
  publishedDate?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas_select".
 */
export interface AreasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  overview?: T;
  keyServices?:
    | T
    | {
        service?: T;
        id?: T;
      };
  attractions?: T;
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues_select".
 */
export interface IssuesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  status?: T;
  area?: T;
  locationText?: T;
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  background?: T;
  actionsUndertaken?: T;
  progressUpdates?:
    | T
    | {
        date?: T;
        update?: T;
        id?: T;
      };
  supportingDocuments?: T;
  relatedNews?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directory-entries_select".
 */
export interface DirectoryEntriesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  area?: T;
  address?: T;
  phone?: T;
  email?: T;
  website?: T;
  description?: T;
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees_select".
 */
export interface CommitteesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  committee?: T;
  photo?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  relatedIssues?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  eventType?: T;
  area?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  description?: T;
  image?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  membershipNumber?: T;
  type?: T;
  adminRevoked?: T;
  revokedReason?: T;
  primaryContact?:
    | T
    | {
        surname?: T;
        firstName?: T;
        phone?: T;
        email?: T;
      };
  postalAddress?: T;
  town?: T;
  postalCode?: T;
  corporateBusinessName?: T;
  additionalMembers?:
    | T
    | {
        surname?: T;
        firstName?: T;
        phone?: T;
        email?: T;
        id?: T;
      };
  subscriptionAmount?: T;
  expiryDate?: T;
  importStatus?: T;
  importFlags?: T;
  linkedAuthUsers?:
    | T
    | {
        authUserId?: T;
        email?: T;
        id?: T;
      };
  lastReminderStage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  membership?: T;
  amount?: T;
  method?: T;
  provider?: T;
  tumaPaymentId?: T;
  paymentStatus?: T;
  confirmedAt?: T;
  confirmedBy?: T;
  rawWebhookPayload?: T;
  paymentType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issue-reports_select".
 */
export interface IssueReportsSelect<T extends boolean = true> {
  referenceCode?: T;
  reporterName?: T;
  reporterPhone?: T;
  reporterEmail?: T;
  reportedBy?: T;
  category?: T;
  description?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
        addressText?: T;
      };
  status?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        changedAt?: T;
        changedBy?: T;
        note?: T;
        id?: T;
      };
  linkedIssue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  orgName: string;
  /**
   * Shown on the homepage hero and in the footer.
   */
  tagline: string;
  /**
   * Falls back to the built-in logo file if left empty.
   */
  logo?: (number | null) | Media;
  contact?: {
    phone?: string | null;
    email?: string | null;
    /**
     * e.g. "Diani, Kenya"
     */
    addressLine1?: string | null;
    /**
     * e.g. "First floor, Diani Beach Shopping Center."
     */
    addressDetail?: string | null;
  };
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'x' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  payment?: {
    paybillNumber?: string | null;
    paybillAccount?: string | null;
    /**
     * e.g. instructions for paying at the Safarilink Office.
     */
    payInPersonText?: string | null;
  };
  seoDefaults?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
  };
  footerLegal?: {
    copyrightName?: string | null;
    builtByText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-navigation".
 */
export interface MainNavigation {
  id: number;
  /**
   * Top nav bar. Leave "children" empty for a plain link with no dropdown.
   */
  headerLinks?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerQuickLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerResourceLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerLegalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Marketing copy (label/description/icon) for issue categories shown in the header dropdown, homepage tiles, and issues page filters. The underlying category values are defined in the Issues collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issue-categories".
 */
export interface IssueCategory {
  id: number;
  categories?:
    | {
        value:
          | 'roads-infrastructure'
          | 'security'
          | 'water-supply'
          | 'electricity'
          | 'waste-management'
          | 'environment'
          | 'beach-access'
          | 'planning-development';
        label: string;
        description?: string | null;
        icon?:
          | (
              | 'information-circle'
              | 'shield-01'
              | 'news'
              | 'calendar-01'
              | 'folder-01'
              | 'call-02'
              | 'road'
              | 'shield-02'
              | 'droplet'
              | 'leaf-01'
              | 'building-01'
              | 'recycle-01'
              | 'checkmark-circle-02'
              | 'notification-01'
              | 'discount-01'
              | 'megaphone-01'
              | 'idea'
              | 'document-attachment'
              | 'target-02'
              | 'shield-user'
              | 'user-group'
              | 'facebook-01'
              | 'mail-01'
              | 'location-01'
            )
          | null;
        /**
         * Show this category as one of the tiles in the homepage "Issues We Are Working On" section.
         */
        featuredOnHomepage?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    heading: string;
    subtext?: string | null;
    /**
     * Falls back to /hero/homepage.jpg if left empty.
     */
    image?: (number | null) | Media;
    ctaButtons?:
      | {
          label: string;
          href: string;
          style?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The icon row of shortcuts just below the hero.
   */
  quickLinks?:
    | {
        label: string;
        sub?: string | null;
        href: string;
        icon?:
          | (
              | 'information-circle'
              | 'shield-01'
              | 'news'
              | 'calendar-01'
              | 'folder-01'
              | 'call-02'
              | 'road'
              | 'shield-02'
              | 'droplet'
              | 'leaf-01'
              | 'building-01'
              | 'recycle-01'
              | 'checkmark-circle-02'
              | 'notification-01'
              | 'discount-01'
              | 'megaphone-01'
              | 'idea'
              | 'document-attachment'
              | 'target-02'
              | 'shield-user'
              | 'user-group'
              | 'facebook-01'
              | 'mail-01'
              | 'location-01'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  newsSection?: {
    eyebrow?: string | null;
    heading?: string | null;
  };
  issuesSection?: {
    eyebrow?: string | null;
    heading?: string | null;
  };
  membershipCta?: {
    heading?: string | null;
    paragraph?: string | null;
    buttonLabel?: string | null;
    benefits?:
      | {
          icon?:
            | (
                | 'information-circle'
                | 'shield-01'
                | 'news'
                | 'calendar-01'
                | 'folder-01'
                | 'call-02'
                | 'road'
                | 'shield-02'
                | 'droplet'
                | 'leaf-01'
                | 'building-01'
                | 'recycle-01'
                | 'checkmark-circle-02'
                | 'notification-01'
                | 'discount-01'
                | 'megaphone-01'
                | 'idea'
                | 'document-attachment'
                | 'target-02'
                | 'shield-user'
                | 'user-group'
                | 'facebook-01'
                | 'mail-01'
                | 'location-01'
              )
            | null;
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  eventsEmptyStateText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
    paragraph?: string | null;
    /**
     * Falls back to /hero/aboutus.jpg if left empty.
     */
    image?: (number | null) | Media;
  };
  /**
   * Areas-served and issues-tracked counts are computed live from the Areas/Issues collections — only their labels are editable here.
   */
  stats?: {
    foundedYear?: string | null;
    membersValue?: string | null;
    membersLabel?: string | null;
    areasServedLabel?: string | null;
    issuesTrackedLabel?: string | null;
  };
  history?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whoWeRepresent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whatWeDoIntro?: string | null;
  whatWeDo?:
    | {
        icon?:
          | (
              | 'information-circle'
              | 'shield-01'
              | 'news'
              | 'calendar-01'
              | 'folder-01'
              | 'call-02'
              | 'road'
              | 'shield-02'
              | 'droplet'
              | 'leaf-01'
              | 'building-01'
              | 'recycle-01'
              | 'checkmark-circle-02'
              | 'notification-01'
              | 'discount-01'
              | 'megaphone-01'
              | 'idea'
              | 'document-attachment'
              | 'target-02'
              | 'shield-user'
              | 'user-group'
              | 'facebook-01'
              | 'mail-01'
              | 'location-01'
            )
          | null;
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Use the token "{count}" in the text of the Committees card to interpolate the live committee count, e.g. "{count} committees and working groups carry out SCRA's work...".
   */
  bottomCtaCards?:
    | {
        title: string;
        text?: string | null;
        linkLabel?: string | null;
        href: string;
        /**
         * Renders this card in the dark/primary style (e.g. "Become a Member").
         */
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-page".
 */
export interface MembershipPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
    paragraph?: string | null;
  };
  tiers?:
    | {
        name: string;
        type: 'personal' | 'household' | 'corporate';
        price: string;
        period?: string | null;
        detail?: string | null;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  tiersFootnote?: string | null;
  benefits?:
    | {
        icon?:
          | (
              | 'information-circle'
              | 'shield-01'
              | 'news'
              | 'calendar-01'
              | 'folder-01'
              | 'call-02'
              | 'road'
              | 'shield-02'
              | 'droplet'
              | 'leaf-01'
              | 'building-01'
              | 'recycle-01'
              | 'checkmark-circle-02'
              | 'notification-01'
              | 'discount-01'
              | 'megaphone-01'
              | 'idea'
              | 'document-attachment'
              | 'target-02'
              | 'shield-user'
              | 'user-group'
              | 'facebook-01'
              | 'mail-01'
              | 'location-01'
            )
          | null;
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  discounts?: {
    heading?: string | null;
    intro?: string | null;
  };
  howToJoin?: {
    heading?: string | null;
    applyButtonLabel?: string | null;
    /**
     * Falls back to Site Settings > Payment > Pay In Person Text if left empty.
     */
    payInPersonText?: string | null;
    footerNote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero eyebrow/heading/paragraph for pages that only need a simple intro block above their CMS-driven list.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-intros".
 */
export interface PageIntro {
  id: number;
  contact?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
    membershipCalloutText?: string | null;
  };
  leadership?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
  };
  committees?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
  };
  directory?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
  };
  issues?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
  };
  news?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
  };
  areas?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
  };
  documents?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
    emptyStateText?: string | null;
  };
  events?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
    emptyStateHeading?: string | null;
    emptyStateText?: string | null;
  };
  map?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
  };
  reportIssue?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
  };
  membershipApply?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Markdown source for the Privacy Policy and Terms of Service pages, rendered client-side via react-markdown — write standard markdown (#/## headings, **bold**, - lists) here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  privacyPolicyMarkdown?: string | null;
  termsOfServiceMarkdown?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  orgName?: T;
  tagline?: T;
  logo?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        addressLine1?: T;
        addressDetail?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  payment?:
    | T
    | {
        paybillNumber?: T;
        paybillAccount?: T;
        payInPersonText?: T;
      };
  seoDefaults?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
      };
  footerLegal?:
    | T
    | {
        copyrightName?: T;
        builtByText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-navigation_select".
 */
export interface MainNavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerQuickLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerResourceLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLegalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issue-categories_select".
 */
export interface IssueCategoriesSelect<T extends boolean = true> {
  categories?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        icon?: T;
        featuredOnHomepage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subtext?: T;
        image?: T;
        ctaButtons?:
          | T
          | {
              label?: T;
              href?: T;
              style?: T;
              id?: T;
            };
      };
  quickLinks?:
    | T
    | {
        label?: T;
        sub?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  newsSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  issuesSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  membershipCta?:
    | T
    | {
        heading?: T;
        paragraph?: T;
        buttonLabel?: T;
        benefits?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  eventsEmptyStateText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
      };
  stats?:
    | T
    | {
        foundedYear?: T;
        membersValue?: T;
        membersLabel?: T;
        areasServedLabel?: T;
        issuesTrackedLabel?: T;
      };
  history?: T;
  whoWeRepresent?: T;
  whatWeDoIntro?: T;
  whatWeDo?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  bottomCtaCards?:
    | T
    | {
        title?: T;
        text?: T;
        linkLabel?: T;
        href?: T;
        featured?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-page_select".
 */
export interface MembershipPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
      };
  tiers?:
    | T
    | {
        name?: T;
        type?: T;
        price?: T;
        period?: T;
        detail?: T;
        featured?: T;
        id?: T;
      };
  tiersFootnote?: T;
  benefits?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  discounts?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  howToJoin?:
    | T
    | {
        heading?: T;
        applyButtonLabel?: T;
        payInPersonText?: T;
        footerNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-intros_select".
 */
export interface PageIntrosSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
        membershipCalloutText?: T;
      };
  leadership?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
      };
  committees?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
      };
  directory?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
      };
  issues?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
      };
  news?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
      };
  areas?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
      };
  documents?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
        emptyStateText?: T;
      };
  events?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
        emptyStateHeading?: T;
        emptyStateText?: T;
      };
  map?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
      };
  reportIssue?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
      };
  membershipApply?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraph?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  privacyPolicyMarkdown?: T;
  termsOfServiceMarkdown?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}