export const documentsData = [
  {
    key: "lotfa-letter",
    filename: "Beach road -Lotfa Junction.pdf",
    title: "Letter to Lotfa Hotel: Wall Obstructing Visibility at Diani Beach Road Junction",
    category: "position-paper",
    publishedDate: "2025-10-13",
    summary: "SCRA letter requesting removal of a wall obstructing visibility at the Diani Beach Road junction near Lotfa Hotel, citing over seven recorded accidents.",
  },
  {
    key: "crow-busters",
    filename: "Diani Crow Busters.pdf",
    title: "Diani Crow Busters: Motorbike Handover Update",
    category: "press-release",
    publishedDate: "2026-06-01",
    summary: "Update announcing a motorbike handover to the Diani Crow Busters team, supporting the Indian house crow control programme.",
  },
  {
    key: "municipal-update",
    filename: "Diani Municipal Update.pdf",
    title: "SCRA Members Update: Diani Municipality Manager",
    category: "county-notice",
    publishedDate: "2026-04-30",
    summary: "Notice announcing Hassan Ali Mwadzugwe as acting Diani Municipality Manager.",
  },
  {
    key: "beach-residences-objection",
    filename: "FORMAL OBJECTION AND MEMORANDUM AGAINST THE PROPOSED MIXED-USE RESIDENTIAL AND HOSPITALITY DEVELOPMENT.pdf",
    title: "Formal Objection: Proposed Diani Beach Residences Development (L.R. No. 16289)",
    category: "position-paper",
    publishedDate: "2026-06-26",
    summary: "SCRA's formal objection to a proposed mixed-use residential and hospitality development on the first row of Diani Beach.",
  },
  {
    key: "roundtable-invite-jul10",
    filename: "INVITATION TO A ROUNDTABLE DISCUSSION ON EVENT PLANNING, REGULATION, AND SHARED RESPONSIBILITY IN DIANI.pdf",
    title: "Invitation: Roundtable on Event Planning, Regulation and Shared Responsibility in Diani",
    category: "public-participation",
    publishedDate: "2026-07-10",
    summary: "Initial invitation proposing a stakeholder roundtable on event planning and regulation in Diani.",
  },
  {
    key: "roundtable-invite-jul16",
    filename: "INVITATION TO A ROUNDTABLE DISCUSSION.pdf",
    title: "Roundtable Discussion Confirmed: Diani Sea Resort, 21 July 2026",
    category: "public-participation",
    publishedDate: "2026-07-16",
    summary: "Confirmation of finalized roundtable details following feedback on the initial invitation.",
  },
  {
    key: "landscaping-letter",
    filename: "Landscapping & Green spaces.pdf",
    title: "Letter to DHOA: Landscaping to Prevent Illegal Structures and Road Encroachment",
    category: "position-paper",
    publishedDate: "2026-06-24",
    summary: "SCRA request to the Diani Hospitality Owners Association for landscaping initiatives along road frontages to deter illegal kiosks and encroachment.",
  },
  {
    key: "destination-diani-memo",
    filename: "MEMORANDUM.pdf",
    title: "Memorandum: Strategic Proposals for Sustainable Event Management and Destination Diani",
    category: "position-paper",
    publishedDate: "2026-07-31",
    summary: "Strategic proposals following the July roundtable, including reactivation of the Destination Diani forum and licensing reform.",
  },
  {
    key: "roundtable-minutes",
    filename: "MINUTES OF THE SCRA ROUND TABLE EVENTS PLANNING MEETING HELD ON 21ST JULY 2026 AT DIANI SEA REOSRT DIANI BEACH AT 9AM.pdf",
    title: "Minutes: Diani Event Planning and Regulation Roundtable, 21 July 2026",
    category: "meeting-minutes",
    publishedDate: "2026-07-21",
    summary: "Full minutes of the multi-stakeholder roundtable on event planning and regulation held at Diani Sea Resort.",
  },
  {
    key: "ntsa-notice",
    filename: "New NTSA Motor Vehicle Inspection Regulations.pdf",
    title: "Notice: New NTSA Motor Vehicle Inspection Regulations",
    category: "county-notice",
    publishedDate: "2026-06-25",
    summary: "Member notice on new NTSA motor vehicle inspection rules commencing July 2026.",
  },
  {
    key: "opening-remarks",
    filename: "OPENING REMARKS - ROUNDTABLE DISCUSSION.pdf",
    title: "Opening Remarks: Diani Event Planning Roundtable",
    category: "meeting-minutes",
    publishedDate: "2026-07-21",
    summary: "SCRA Chairman's opening remarks at the Diani event planning and regulation roundtable.",
  },
  {
    key: "power-lines-letter",
    filename: "OVERHEAD POWER LINES IN DIANI.pdf",
    title: "Letter to KPLC: Dangerous Billboards Obstructing Overhead Power Lines",
    category: "position-paper",
    publishedDate: "2026-06-25",
    summary: "SCRA letter to Kenya Power requesting removal of billboards encroaching on overhead power line wayleaves following a blackout incident.",
  },
  {
    key: "property-magazine",
    filename: "Property Magazine write up 2026.pdf",
    title: "Shaping the Future of Coastal Investment: The SCRA Blueprint for Sustainable Growth",
    category: "press-release",
    publishedDate: "2026-05-25",
    summary: "Feature article on SCRA's role in protecting property value and guiding sustainable growth on the South Coast.",
  },
  {
    key: "roundtable-program",
    filename: "ROUNDTABLE DISCUSSION.pdf",
    title: "Programme: Diani Event Planning and Regulation Roundtable",
    category: "meeting-minutes",
    publishedDate: "2026-07-21",
    summary: "Official programme and session schedule for the 21 July 2026 roundtable.",
  },
  {
    key: "development-advisory",
    filename: "SCRA Development Advisory.pdf",
    title: "Advisory on Responsible Property Development, Community Consultation and Legal Compliance",
    category: "planning-guideline",
    publishedDate: "2026-06-13",
    summary: "SCRA advisory to residents and developers on legal compliance frameworks for property development on the South Coast.",
  },
  {
    key: "elc-newsletter",
    filename: "IN THE ENVIRONMENT & LAND COURT AT KWALE ELC CASE NO. 12 OF 2021.pdf",
    title: "Member Newsletter: ELC Case No. 12 of 2021 Ruling",
    category: "press-release",
    publishedDate: "2023-12-21",
    summary: "SCRA newsletter explaining the significance of the Environment and Land Court ruling in ELC Case No. 12 of 2021.",
  },
  {
    key: "elc-judgement",
    filename: "The judgement.pdf",
    title: "Judgement: ELC Case No. 12 of 2021 (Kwale)",
    category: "position-paper",
    publishedDate: "2023-12-21",
    summary: "Full court judgement ordering alteration or demolition of non-compliant units on parcel Kwale/Diani Beach/800 and 801.",
  },
]
