export const postsData2 = [
  {
    title: 'SCRA Achievements Over the Last 18 Months',
    slug: 'scra-achievements-18-months',
    excerpt: 'A round-up of SCRA advocacy wins across planning, security, environment, and noise pollution.',
    content:
      "SCRA successfully joined a court case against a developer to halt construction of a block of flats that violated zoning plan rules and other regulations, securing a stop order. The case remains ongoing, with SCRA seeking demolition of the illegal construction. SCRA also confirmed that, in the absence of an updated zoning plan, the existing plan remains legally in effect despite its expiry date.\n\nSCRA alerted the National Museums of Kenya to a mosque construction project that threatened an archaeologically valuable site.\n\nFollowing several meetings between SCRA and local security agencies, the OCS and OCPD in Ukunda were transferred, after which frequent armed gate robberies in the area stopped.\n\nSCRA now maintains a working relationship with several Kwale and national authorities, particularly NEMA, which responds promptly to issues SCRA raises.\n\nSCRA organised a visit by the National Environmental Complaints Committee (NECC) to several sites in Diani and Tiwi. The committee made strong recommendations on beach and beach-access-road encroachment as well as illegal stone mining in Tiwi. SCRA is following up on these recommendations directly with the NECC and Kwale County Government, in partnership with the Kenya Alliance of Residents' Associations (KARA).\n\nSCRA was instrumental in the installation of speed limit signage along Diani Beach Road.\n\nSCRA procured two decibel meters for noise pollution monitoring, donating one to the Kwale County Government's noise pollution agency.\n\nSCRA welcomed two new committee members: Wambui Ngunya (lawyer) and George Jaramba (human rights).",
    publishedDate: '2024-02-27',
  },
  {
    title: 'Meeting Notes and Site Visits: SCRA and the Environmental Complaints Committee (ECC)',
    slug: 'ecc-site-visit-february-2021',
    excerpt:
      'Notes from a joint site visit with the national Environmental Complaints Committee across multiple beach access road encroachment sites in Diani and Tiwi.',
    content:
      "On Saturday 27th February 2021, SCRA met with the Environmental Complaints Committee (ECC) to present its report on the blocking and encroachment of beach access roads and other illegal developments. SCRA was represented by Onesmus Macharia, George Jaramba, and Gerald Gambo, alongside a seven-member ECC team, a representative from the county commissioner's office, and representatives from Fisheries and the Kwale planning office.\n\nAt Mvureni, near the Fishermen's Restaurant, village elders and chiefs reported that land at local fish landing sites had been taken over, forcing construction onto the access road itself. NEMA had already ordered the restaurant and other structures on the access road to be converted to temporary structures and eventually removed, though no timeline had been set.\n\nAt the Mwaepe (KFI) beach access road, the team found part of the road had reportedly been encroached upon and was told a blocking restaurant would need to be removed; local fishermen and beach operators raised their concerns directly with the ECC.\n\nAt Bidi Badu, the ECC team found extensive informal construction along the beach and committed to remedial action after meeting with beach operators.\n\nAt a large construction site on a plot still under litigation, county and planning office representatives expressed surprise that building work was continuing despite a prior stop order.\n\nNear the Kongo Mosque, the team inspected a restaurant encroaching on the access road and spoke with mosque representatives. A high wall was also found blocking access near the Mwachema river on the Tiwi side, reportedly cutting off the Kaya Tiwi sacred site from public access.\n\nAt Southern Palms, a mosque under construction was found to be blocking most of a beach access road, again reportedly due to adjacent land being taken over.\n\nAt stone quarrying sites in Tiwi, the ECC team observed environmental damage from quarrying, much of it on land belonging to absentee landowners, and raised concerns about noise and dust pollution.\n\nThe ECC committed to submitting a report and recommendations to the Cabinet Secretary for Environment within two weeks and asked SCRA to continue serving as its eyes and ears on the ground, in coordination with NEMA, the planning office, Kwale County Government, the Water Resources Authority, KWS, WWF, and the National Museums of Kenya.",
    publishedDate: '2021-02-27',
  },
]
